### Gimbal PID control for dragon quad type

# general parameter
controller/baselink: fc
controller/only_three_axis_mode: true
controller/verbose: true
controller/real_machine: false
controller/control_verbose: false
controller/joints_torque_control_srv_name: /dragon/joints/torque_enable
controller/gimbals_torque_control_srv_name: /dragon/gimbals/torque_enable

# alt [N]
controller/alt/offset: 0
controller/alt/limit: 28
controller/alt/p_term_limit: 28
controller/alt/i_term_limit: 28
controller/alt/d_term_limit: 28
controller/alt/alt_landing_const_i_ctrl_thresh: -0.3

# xy [rad]
controller/xy/p_gain: 3.6 # old: 2.5 # 10 / 7.38: sucess in real machine, but weak; divided by mass
controller/xy/i_gain: 0.03 # divided by mass
controller/xy/hovering_i_gain: 0.03 # divided by mass
controller/xy/d_gain: 4 # 40.0 / 7.38 # 20 / 7.38: sucess in real machine, but weak; divided by mass
controller/xy/limit: 100 # divided by mass
controller/xy/p_term_limit: 10 # [m/s^2] divided by mass
controller/xy/i_term_limit: 10 # [m/s^2] divided by mass
controller/xy/d_term_limit: 10 # [m/s^2] divided by mass
controller/xy/x_offset: 0
controller/xy/y_offset: 0

# yaw [N]
controller/yaw/limit: 10.0
controller/yaw/p_term_limit: 10.0
controller/yaw/i_term_limit: 10.0
controller/yaw/d_term_limit: 10.0
controller/yaw/p_gain: -10 # should be negative
controller/yaw/i_gain: 0.1
controller/yaw/d_gain: -5 # should be negative

# pitch & roll
controller/pitch_roll/control_p_det_thresh: 0.00025
controller/pitch_roll/control_rate_thresh: 0.7
controller/pitch_roll/limit: 20.0
controller/pitch_roll/p_term_limit: 20.0
controller/pitch_roll/i_term_limit: 20.0
controller/pitch_roll/d_term_limit: 20.0
controller/pitch_roll/p_gain: 20 
controller/pitch_roll/i_gain: 2.0 
controller/pitch_roll/d_gain: 0.5 #pitch big noise from gyro

# desire tilt
controller/tilt_pub_interval: 0.2

# gimbal vectoring function check
controller/gimbal_vectoring_check_flag: false
