servo_controller:
  joints:
    state_sub_topic: servo/states
    ctrl_pub_topic: servo/target_states
    torque_pub_topic: servo/torque_enable
    angle_sgn: 1
    angle_scale: 0.00076699
    zero_point_offset: 2047
    torque_scale: 0.03483 # convert to N*m

    # for simulation
    simulation:
      pid: {p: 100.0, i: 1, d: 2.0, i_clamp_max: 6.6, i_clamp_min: -6.6}
      type: effort_controllers/JointPositionController

    controller1:
      id: 0
      name: joint1
      simulation:
        init_value: 1.4
    controller2:
      id: 2
      name: joint2
      simulation:
        init_value: 1.5708
    controller3:
      id: 4
      name: joint3
      simulation:
        init_value: 1.5708

  gimbals:
    ctrl_pub_topic: servo/target_states
    torque_pub_topic: servo/torque_enable
    angle_sgn: -1
    angle_scale: 0.001534
    zero_point_offset: 0

    simulation:
      pid: {p: 10.0, i: 0.3, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
      type: effort_controllers/JointPositionController

    controller1:
      id: 1
      name: gimbal1
      simulation:
        init_value: 3.1415

    controller2:
      id: 3
      name: gimbal2
      simulation:
        init_value: 0.0

    controller3:
      id: 5
      name: gimbal3
      simulation:
        init_value: 3.1415

    controller4:
      id: 6
      name: gimbal4
      simulation:
        init_value: 0.0
